[project]
name = "playfile-cli"
version = "0.1.0"
description = "CLI tool for Playfile - AI-powered development workflows"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "playfile-core",
    "click>=8.1.0",
    "rich>=13.0.0",
    "claude-agent-sdk>=0.1.0",
]

[project.scripts]
pf = "playfile_cli.main:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
playfile-core = { workspace = true }

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "UP"]

[tool.pyright]
typeCheckingMode = "strict"
pythonVersion = "3.11"
