[project]
name = "playfile-utils"
version = "0.1.0"
description = "Shared utilities for Playfile"
readme = "README.md"
authors = [
    { name = "Sofiane Djerbi", email = "sofiane.djerbi38@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"
